USE `LearnWords`;

DROP TABLE IF EXISTS `sentences`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sentences` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `native` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `foreignWord` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `sentences`
--

LOCK TABLES `sentences` WRITE;
/*!40000 ALTER TABLE `sentences` DISABLE KEYS */;
INSERT INTO `sentences`(`native`, `foreignWord`) VALUES 
("1) Mióta vársz magasabb életszínvonalra?", "1) How long have you been waiting for a higher standard of living?"),
("2) Mióta próbálja visszaszerezni?", "2) How long has he been trying to get it back?"),
("3) Mióta tervezik, hogy összeházasodnak?", "3) Since when have they been planning to get married?"),
("4) 6 éve vagyok nos/férjnél.", "4) I have been married for 6 years."),
("5) Elso találkozásunk óta szeretlek.", "5) I have been in love with you since we first met."),
("6) Már öt perce boldog.", "6) She has been happy for 5 minutes."),
("7) 1986 óta tanár.", "7) She has been a teacher since 1896."),
("8) 27 éve katona.", "8) He has been a soldier for 27 years."),
("9) Meddig maradsz még Budapesten?", "9) How long are you staying in Budapest?"),
("10) Mióta vagy Budapesten?", "10) How long have you been staying in Budapest?"),
("11) Nyár óta csak rád gondolok.", "11) I’ve been thinking of you since summer."),
("12) Már három hete dolgozom.", "12) I’ve been working for three weeks."),
("13) Tizennégy éves kora óta ír naplót.", "13) She’s been keeping a diary since she was fourteen."),
("14) Dél óta alszik.", "14) He has been sleeping since noon."),
("15) Már öt perce szól a telefon.", "15) The phone has been ringing for five minutes."),
("16) Azóta horkol, mióta kivették a manduláját.", "16) He has been snoring since his tonsils were removed."),
("17) Mióta tanítasz?", "17) How long have you been teaching?"),
("18) Két napja nyüszög.", "18) He’s been whining for two days."),
("19) Tavaly óta cigarettázik.", "19) He has been smoking since last year."),
("20) Órák óta azt az egy halat eszi.", "20) She’s been eating that fish for hours."),
("21) Mióta miniszter lett, autóval jár.", "21) He has been travelling in a car since he became a minister."),
("22) Már egy hete csak a mamára gondolok.", "22) I’ve been thinking of mum for a week."),
("23) Osz óta az öbölben úsznak a magányos hattyúk.", "23) The lonely swans have been floating in the bay since autumn/fall."),
("24) Mióta jár Jóska Gézával?", "24) How long has Joe been dating Géza?"),
("25) Már egy hete csak a mamára gondolok.", "25) I've been thinking of Mum for a week now."),
("26) Még fél évig sem éltek együtt, mikor elváltak.", "26) They had been living together for less than half a year when they got divorced."),
("27) Mióta megnosült, egész másképp viselkedik.", "27) Since she got married, she's been behaving rather differently."),
("28) Egész nap úgy hiányoztál.", "28) I've been missing you all day."),
("29) Te jó isten, mennyit ittál! Nyugi, anyukám, nem ittam többet, mint a Józsi, pedig o már tegnap elkezdte, és még most sem fejezte be.", "29) Oh, my God, you've been drinking a lot! Easy, mum, I haven't drunk more than Joe, mind you, he started it yesterday and hasn't finished it yet."),
("30) Három éve hordja azt a rongyos farmert.", "30) She's been wearing that shabby pair if jeans for three years."),
("31) Mióta megláttalak a bokrok alatt, csak rólad álmodom.", "31) I've been dreaming about you since I saw you under the bushes."),
("32) Mióta megérkezett a városba, a legdrágább szállodában lakik.", "32) Since he arrived in town, he has been living in the ritziest hotel."),
("33) Úgyhogy most három napja táncol.", "33) So now she's been dancing for three days."),
("34) Egy hete lakom a California szállodában.", "34) I've been living in the Hotel California for a week."),
("35) Már egy órája olvassa azt a kurta cikket.", "35) Ha has been reading that short article for an hour already."),
("36) Ablakot nyitottam.", "36) I have opened the window."),
("37) Megcsókolta (és most várandós).", "37) He has given her a kiss."),
("38) Lábát törte, így nem jöhet velem diszkózni.", "38) He has broken his leg he can’t come with me to the disco."),
("39) Jártam már Tótkomlóson.", "39) I have already been to Tótkomlós."),
("40) Háltam már lópokrócon.", "40) I’ve already slept on a horse blanket."),
("41) Még nem jártam Tótkomlóson.", "41) I haven’t been to Tótkomlós yet."),
("42) Még sosem háltam lópokrócon.", "42) I’ve never slept on a horse blanket."),
("43) Jártál te már Tótkomlóson?", "43) Have you ever been to Tótkomlós?"),
("44) Háltál te már lópokrócon?", "44) Have you slept on a horse blanket yet?"),
("45) Épp most jártam Tótkomlóson.", "45) I’ve just been to Tótkomlós."),
("46) Épp most háltam lópokrócon.", "46) I’ve just sleep on a horse blanket."),
("47) Ma reggel jártam Tótkomlósan.", "47) I’ve been to Tótkomlós this morning."),
("48) E héten háltam lópokrócon.", "48) I’ve slept on a horse blanket this week."),
("49) Végre már ezt is megtanultam.", "49) I have learnt it now."),
("50) De hisz ezt már tanultam.", "50) I have already learnt it."),
("51) Még nem tanultam meg.", "51) I haven’t learnt it yet."),
("52) Még mindig nem kérdeztem meg.", "52) I still haven’t asked him."),
("53) Épp most ment el hazulról.", "53) She has just left home."),
("54) Egész mostanáig boldogok voltunk.", "54) We have been very happy until recently."),
("55) Én még ilyet nem láttam!", "55) I haven’t seen anything like that."),
("56) Nem találkoztunk mi már valahol?", "56) Haven’t we met somewhere before?"),
("57) Bocsánatot kértél már tole?", "57) Have you apologized to him yet?"),
("58) Már olvastam.", "58) I’ve already read it."),
("59) Kicsit meghíztál, nem?", "59) You’ve put a bit weight on, haven’t you?"),
("60) A kezét már megkérte, de még nem vette el.", "60) He’s already popped the question, but he hasn’t married yet."),
("61) Még sose féltem így.", "61) I’ve never been so scared."),
("62) Még mindig nem felelt.", "62) He hasn’t yet answered. (He still hasn’t answered.)"),
("63) Elaludtál már?", "63) Have you gone to sleep yet?"),
("64) Épp most dugta el.", "64) She’s just hidden it."),
("65) Évek óta nem ettem ilyen jó véreshurkát.", "65) I haven't eaten such good blood pudding for years."),
("66) A mai napig nem felejtettem el azt a szeptemberi estét, mikor eloször láttalak meg a szénakazal tövibe'.", "66) I haven't forgotten the night in September when I first saw you in the shade of the haybale."),
("67) Már 10 éve barátnok.", "67) They've been friends for ten years."),
("68) Majd szólok, ha befejeztem.", "68) I'll tell you when I've finished."),
("69) Megkaptad már a pénzt?", "69) Have you received the money yet?"),
("70) Kettokor jöttek meg, de azóta se láttuk oket.", "70) They arrived at two we haven't seen them ever since."),
("71) Az összes húst bepaníroztad?", "71) Have you coated all the meat with breadcrumbs?"),
("72) Nem találkoztunk mi már valahol?", "72) Haven't we met somewhere before?"),
("73) Még soha nem volt ilyen fejfájásom.", "73) I've never had such a headache."),
("74) Láttál te már felnott férfit meztelen?", "74) Have you ever seen a brown man naked?"),
("75) Megetted már amit tegnap foztem?", "75) Have you yet eaten what I cooked yesterday?"),
("76) A cipojét és a kabátját levette, az ingét épp most gombolja, de a fülbevalóját még nem kattintotta ki.", "76) She has taken off her shoes and coat, she's undoing her louse right now, but she hasn't unclipped her earrings yet."),
("77) Mondtam már neked, hogy ne szopd az ujjad!", "77) I've already told you not to suck your finger!"),
("78) Megjavítottad már a csapot?", "78) Have you repaired the tap yet?"),
("79) Elfogyott a cigarettám.", "79) I've run out of cigarettes."),
("80) Befejezted már?", "80) Have you finished yet?"),
("81) Nem említettem még neked azt az esetet, mikor véletlenül rossz buszra szálltam?", "81) Haven't I mentioned to you the case when I accidentally took the wrong bus?"),
("82) Ugye még nem meséltem azokról az idokrol, mikor kéz a kézben mentünk a Dózsa György úton május 1-jén?", "82) I haven't told you about the days when we were walking hand in hand on Dózsa György road on May Day, have I?"),
("83) Felfújta a lufit, és az most akkora, mint egy ház.", "83) He has blown up the balloon and now it's as big as a house."),
("84) Most már befejeztem.", "84) I've finished it now."),
("85) Meglocsoltad már a feleséged? Ot még nem locsoltam meg, de a barátnomet már igen. Tegnap mentem hozzá és kaptam tole piros tojást. A feleségemtol piros tojást még nem kaptam, de a sodrófát már elovette. Még nem csapott a fejemre, de nagyon félek, mert tavaly úgy kupán vágott, hogy még most sem ment le a púp a fejemrol.", "85) Have you sprinkled your wife? No, I haven't, but I've already sprinkled my girlfriend. I went to her place yesterday and I got a red egg from her. I haven't got a red from my wife yet, but she has already produced the rolling pin. She hasn't yet hit me on the head but I'm scared because last year she hit me on the head so hard that the lump hasn't gone down from my head yet."),
("86) Ittam egy kis kólát, és most csuklok.", "86) I've drunk some coke and now I'm hiccuping."),
("87) Te csöngettél, Tasziló?", "87) Have you rung the bell, Tasziló?"),
("88) A hullámvasúton már ültem, de az elvarázsolt kastélyban még nem voltam.", "88) I've already traveled on the roller coaster but I haven't been to the haunted castle."),
("89) Ivott egy pohár vodkát és most itt kacsázik az utcán.", "89) He has drunk a glass of vodka and now he's zigzagging in the street."),
("90) Még sosem volt ilyen szerencsém.", "90) I've never been so lucky."),
("91) Én még sohasem utaztam a szellemvasúton, soha sem láttam a nagy sárkányt.", "91) I have never ever traveled on the ghost train, I have never ever seen the large dragon."),
("92) Láttál te már mackót málnásban?", "92) Have you ever seen a bear in raspberries?"),
("93) Sok kérdést már megoldottunk.", "93) We have solved a lot of problems."),
("94) Én még sose voltam férfivel.", "94) I've never been with a man before."),
("95) Sokszor voltam már ideges.", "95) I've been nervous lots of times."),
("96) Szakítottam Józsival.", "96) Me and Joe have had a bust up."),
("97) Olvastad már?", "97) Have you read it yet?"),
("98) Amikor majd elolvasod, légyszives add ide.", "98) When you've read it, please give it to me."),
("99) Amikor befejezi, összesen hat napja fog táncolni.", "99) When she has finished, she'll have been dancing for six days altogether."),
("100) Ugye milyen sokat javult az életszínvonaluk? De idétlen vagy.", "100) Our living standard has improved greatly, hasn't it? How stupid can you get!"),
("101) Épp TV-t név.", "101) He is watching TV now."),
("102) Most áll, vagy ül?", "102) Is she sitting or standing?"),
("103) Általában 7-kor kel, de e héten 8-kor.", "103) He usually gets up at 7, but this week he is getting up at 8."),
("104) Általában Camparit iszik, de ma este kevertet.", "104) She generally drinks Campari, but this evening she is drinking “kevert”."),
("105) Állandóan ezt a hülye disco-lemezt hallgatja!", "105) He is always listening to that stupid disco record!"),
("106) Állandóan hazudsz!", "106) You are always telling me lies!"),
("107) Most már tudom.", "107) Now I know.");

/*!40000 ALTER TABLE `sentences` ENABLE KEYS */;
UNLOCK TABLES;