USE `LearnWords`;

LOCK TABLES `sentences` WRITE;
/*!40000 ALTER TABLE `sentences` DISABLE KEYS */;
INSERT INTO `sentences`(`native`, `foreignWord`) VALUES ("108) Áh, most már emlékszem.", "108) Oh, now I remember."),
("109) Holnap este színházba megyek.", "109) I am going to the theatre tomorrow night."),
("110) Mit csinálsz?", "110) What are you doing?"),
("111) Hova mész?", "111) Where are you going?"),
("112) Most hülyéskedsz?", "112) Are you kidding?"),
("113) Hull az elsárgult levél.", "113) The yellow leaves are falling."),
("114) Almát eszem.", "114) I’m eating an apple."),
("115) Ülök egy rózsaszínu kádban.", "115) I’m sitting in a pink bathtub."),
("116) Majd holnap kimegyek a piacra.", "116) I’m going to market tomorrow."),
("117) Állandóan csapkodja az ajtót.", "117) He is always slamming the door."),
("118) Sírok.", "118) I am crying."),
("119) Írok.", "119) I am writing."),
("120) Most épp nem írok, nem olvasok.", "120) I’m not writing or reading."),
("121) Gondolkodom.", "121) I’m thinking."),
("122) A buszra várok.", "122) I’m waiting for the bus."),
("123) Csöng a telefon.", "123) The phone’s ringing."),
("124) Ez kezd bedilizni.", "124) He’s cracking up."),
("125) Kati holnap jön át.", "125) Kate is coming round tomorrow."),
("126) Állandóan vitatkoznak.", "126) They’re always arguing."),
("127) Lehúnyja kék szemét az ég.", "127) The sky is closing its blue eyes."),
("128) Alszik a széken a kabát.", "128) The coat is sleeping on the chair."),
("129) Hé, mit csinálsz te itt?", "129) Hey, what are you doing here?"),
("130) Ezen a tavaszon fogok férjhez menni.", "130) I'm going to get married this spring."),
("131) Itt ül az ido a nyakamon.", "131) Time is sitting on my neck."),
("132) Nincs hozzászokva ahhoz, hogy busszal járjon a piacra.", "132) She is not used to going to the market by bus."),
("133) Ezt a sört most megiszom.", "133) I'm going to drink this beer now."),
("134) Most épp nem alszik.", "134) She's not sleeping right now."),
("135) Hová mész te kisnyulacska?", "135) Where are you going bunny?"),
("136) Ballag a katona, szájában csutora.", "136) The GI is trudging with a mouthpiece in his mouth."),
("137) Apu, mit csinál a kutya a fánál?", "137) Daddy, what's the dog doing by the tree?"),
("138) Állandóan újságot olvas reggeli közben.", "138) He is always reading a paper during breakfast."),
("139) Hu de köhögsz. Csak nem fáztál meg?", "139) Hey, you are coughing a lot. I hope you haven't caught a cold."),
("140) Hegyek között, völgyek között zakatol a vonat.", "140) The train is rattling along between mountains and valleys."),
("141) Csörög a lánc. Mi? Csörög a lánc. Nem hallom, mert csörög a lánc.", "141) The chain is rattling! What? The chain is rattling! I can't hear you 'cause the chain is rattling."),
("142) Mit sütsz kis szucs? Sós húst sütsz kis szucs?", "142) What are you frying little furrier? Are you frying salty meat, furrier?"),
("143) Süt a pék, süt a pék gezemice lángost.", "143) The baker is frying, the baker is frying hotchpotch dough."),
("144) Perceg a szú.", "144) The woodworm is ticking away."),
("145) Állandóan csapkodja az ajtót.", "145) He is always slamming the door."),
("146) Egy fekete macska ül a fogason.", "146) A black cat is sitting on the rack."),
("147) Ezért megfizetsz!", "147) You're going to pay for this."),
("148) Hull az elsárgult levél.", "148) The yellow leaves are falling."),
("149) Hol lesz a hétvégi buli?", "149) Where's the party gonna be this weekend?"),
("150) Melyik horkol?", "150) Which one is snoring?"),
("151) Idáig vagyok az üzleti problémáiddal.", "151) I'm having to here with your business problems."),
("152) Londonban üzletel.", "152) He's doing some deal in London now."),
("153) Halálra untatsz.", "153) You're boring me stiff."),
("154) Most is olvas.", "154) He's reading right now."),
("155) Csakazértis el fogom olvasni.", "155) I'm going to read it."),
("156) Gyakran megyünk moziba.", "156) We often go to the cinema."),
("157) Az állatok sosem ölnek pénzért.", "157) Animals never kill each other for money."),
("158) Éjfélkor szokott lefeküdni.", "158) She usually goes to bed at midnight."),
("159) A Nap keleten kel.", "159) The sun rises in the East."),
("160) Szeretlek.", "160) I love you."),
("161) Utálom az esot.", "161) I hate rain."),
("162) Itt jön a Nap.", "162) Here comes the sun. (Beatles)"),
("163) Ott megy az álmunk.", "163) There goes our dream."),
("164) Ismerlek.", "164) I know you."),
("165) Szabad akarok lenni.", "165) I want to break free."),
("166) Érted?", "166) Do you understand?"),
("167) Mindenre emlékszem.", "167) I remember everything."),
("168) Azt hiszem igazad van.", "168) I think you are right."),
("169) Remélem érted a könyvet.", "169) I hope you see through the book."),
("170) Úgy értem, hogy pénteken nem érek rá.", "170) I mean I’m busy on Friday."),
("171) Úgy tudom ruhákat ad és vesz.", "171) I believe you buy and sell clothes."),
("172) Éjjel nappal rád gondolok.", "172) I think about you night and day."),
("173) Korán szoktam kelni.", "173) I usually get up early."),
("174) Néha nyolcig alszik.", "174) Sometimes she sleeps until eight."),
("175) Tetszem neked?", "175) Do you like me?"),
("176) Nem ízlik a leves.", "176) I don’t like the soup."),
("177) Soha nem segít.", "177) She never helps me."),
("178) Minden nap felkel a Nap.", "178) The sun rises every day."),
("179) Futni szoktam, de úszni nem járok.", "179) I usually go running but I never go swimming."),
("180) Én nem golfozom.", "180) I never play golf."),
("181) Minden este fest.", "181) She paints every evening."),
("182) Utálom a birkahúst.", "182) I hate mutton."),
("183) Ritkán sír, de gyakran nevet.", "183) She seldom cries but often laughs."),
("184) Remélem jól vagy.", "184) I hope you are fine."),
("185) Itt jön.", "185) Here he comes."),
("186) Szeretlek.", "186) I love you."),
("187) Hányszor mosol naponta fogat?", "187) How many times a day do you clean your teeth?"),
("188) Józsi bácsi már nem dolgozik itt.", "188) Józsi bácsi doesn't work here anymore."),
("189) Malacka minden nap meglátogatja Micimackót.", "189) Piglet goes to see Winnie-the-Pooh every day."),
("190) Hol élsz te?", "190) Where do you live?"),
("191) Te kinek drukkolsz?", "191) Who do you support?"),
("192) Mindig este zuhanyozok, mert reggel rohanok.", "192) I always take a shower in the evening because in the morning I'm in a hurry."),
("193) Szereted a mézet?", "193) Do you like honey?"),
("194) Szeretsz még, mondd?", "194) Tell me, do you still love me?"),
("195) Érted?", "195) Do you understand?"),
("196) Azt hiszem, én értem.", "196) I think I understand."),
("197) Milyen nap van ma?", "197) What day is today?"),
("198) Minden kártya nálad van.", "198) You hold every card."),
("199) Mindig azt mondod, hogy visszafogott vagyok.", "199) You always say I'm too reserved."),
("200) Sose olvas.", "200) He never reads."),
("201) Néha olvas.", "201) Sometimes he reads."),
("202) Minden este étteremben vacsorázik.", "202) He has dinner in a restaurant every evening."),
("203) Mikor felébredtem, már 10 perce ment a vonat.", "203) When I woke up, the train had been going for ten minutes."),
("204) Mikor a sarokra értem, a lány már 20 perce ott várt.", "204) When I got to the corner, the girl had been waiting for twenty minutes."),
("205) Már tíz perce gépelt, mikor látta, hogy nincs papír a gépben.", "205) He had been typing for ten minutes when he saw there was no sheet in the typewriter."),
("206) Mikor felébredt, a kakas már fél órája kukorékolt.", "206) When he woke up, the cock had been crowing for half an hour."),
("207) Még csak öt perce ettek, mikor újabb vendégek érkeztek.", "207) They had only been eating for five minutes when more guests arrived."),
("208) Már egy órája ugatott a kutya, mikor végre kiment.", "208) The dog had been barking for an hour when at least he went out."),
("209) Nagy elánnal bontotta a csirkét, amikor rájött, hogy nincs otthon zsír.", "209) She had been easily carving up the chicken when she realized there was no lard at home."),
("210) Órák hosszat ült a rókalyuk elott, mikor végre feltunt egy nyuszi.", "210) He had been sitting at the fox-hole for hours when at least a hare/rabbit/bunny showed up."),
("211) Még tíz percet sem vezetett a forgalomban, mikor a vizsgabiztos megkérte, hogy cseréljenek helyet.", "211) She had been driving in the traffic for less than 10 minutes when the examiner asked her to change seats."),
("212) Már vagy három órája nyomta a csengot, mikor a házmester végre kinézett.", "212) He had been ringing the bell for three hours when the caretaker looked out at last."),
("213) Már két órája beszélt, mikor rájött, hogy senki nincs a szobában.", "213) She had been talking for two hours when she realized there was nobody in the room."),
("214) Magas lovon ült, mielott lebukott.", "214) He had been riding high before he had a fall."),
("215) Tegnap már két napja táncolt.", "215) Yesterday she had been dancing for two days."),
("216) Csak olvasta, olvasta, mikor látta, hogy fejjel lefelé van.", "216) He had been reading and reading when he saw it was upside down."),
("217) Mire kiért az állomásra, a vonat már elment.", "217) By the he got to the station, the train had already left."),
("218) Mire rájöttem, hogy szélhámos, már összetört a szívem.", "218) When I realized she was a swindler, she had already broken my heart."),
("219) Dühös voltam rá, mert elfelejtete föladni a levelet.", "219) I was angry with him because he had forgotten to post the letter."),
("220) Mire a vadász megtöltötte a pukáját, a nyuszi már elszaladt.", "220) By the time the hunter had loaded his gun, the hare had already run away."),
("221) Mielott elszaladt, sárgarépát dugott a puska csövébe.", "221) Before she run away she had put a carrot into the muzzle of the rifle."),
("222) Már rég megsavanyodott a túró rudi, mire rászánta magát, hogy megegye.", "222) CCR (Cottage Cheese Rudolph) had gone sour long before he brought himself to eat it.");

/*!40000 ALTER TABLE `sentences` ENABLE KEYS */;
UNLOCK TABLES;